### ISSUE TITLE
Koodikatselmointi 2

### ISSUE THREAD

**Issue by Erkkapyy** [ziigaa/MacroScript#2]
- Projektisi aihe on hyvin mielenkiintoinen ja vaikutti mielestäni aluksi melko kompleksiselta, mutta luettuani metodisi kommentoinnit ohjelman rakenne selveni huomattavasti.

- Ohjelma toimii hyvin, ja antamasi käyttöohjeet ovat selkeät. Sain suoritettua muutamat scriptit joilla liikutin hiirtä notepadin ylle, painoin vasempaa klikkiä ja kirjoitin jotain.

- Koodisi noudattaa Clean code periaatetta.

- Koodin olisi ehkä voinut jakaa paketteihin? Mutta itseäni ei ainakaan haitannut että kaikki oli yhdessä paketissa.

- Jatkokehitysvinkkinä, kuten useissa muissa macro ohjelmissa voisit antaa käyttäjän asettaa pikanäppäimen "run script" toiminnolle.

**Comment by ziigaa** [comment]
Kiitos palautteesta! Mukava kuulla, että pidit työstäni :) 
Jaoin projektin ja testit paketteihin :) Mietin aikaisemmin start/stop komentoja pikanäppäinten avulla, mutta tämä olisi jälleen vaatinut uuden luokan ja projekti tuntuu mielellään paisuvan vähän joka suuntaan, joten jouduin toistaiseksi luopumaan ajatuksesta. En tiedä vielä varmaksi, että toteutanko toimintoa tämän kurssin puitteissa, mutta jos tämä jää harrasteluprojektiksi, niin miksipä ei :)
